### ISSUE TITLE
↩️ Displaying newlines and EOFs?

### ISSUE THREAD

**Issue by favonia** [RedPRL/asai#112]
Inspired by @mikeshulman's suggestion, perhaps it's useful to display newline characters and/or the end-of-file. I can think of a few choices:

- Newline: `␤` `⏎` `↲` `↵`
- End of file: `␄` `⌁` `¶` `⏹`

**Comment by favonia** [comment]
It still seems annoying to _represent_ a span/range that marks the EOF, though. :thinking:

**Comment by mikeshulman** [comment]
I don't quite understand what you mean by "represent"?

**Comment by favonia** [comment]
> I don't quite understand what you mean by "represent"?

I believe the idea is to write down the range that marks the EOF as `[len,len)` where `len` is the size of the file/string. Suppose the whole file has exactly two characters. The EOF will be represented as `[2,2)`.

The trouble is that this seems to break the range algebra, which assumes the following laws:

1. `[i,j)` and `[j,k)` are disjoint, but the disjoint union of them is exactly `[i,k)`.
3. `[i,l)` contains `[j,k)` if and only if `i <= j` and `k <= l`.

Suppose the whole file is of length 2. The range `[1,2)` must contain the EOF as well, but then `[1,2)` and `[2,2)` are no longer disjoint. The end-of-file is different from newlines because newline sequences do occupy actual bytes.

One possibility is to use `[len,len+1)` for EOF. I haven't checked how other libraries/programs handle it...

**Comment by mikeshulman** [comment]
Is there any situation in which one would want to talk about a range that includes EOF and *also* other characters?  If not, then I would be inclined to just treat EOF as a separate condition rather than any pair of offsets.

**Comment by favonia** [comment]
I think we solved the EOF. I now feel showing newlines might be useless. @mikeshulman Do you have other relevant requests? Or I'll close this issue. :-)

**Comment by mikeshulman** [comment]
The EOF interface and display looks good to me.  Thanks!
