### ISSUE TITLE
🔤 making short code optional?

### ISSUE THREAD

**Issue by favonia** [RedPRL/asai#117]
Both LSP and Rust do not demand a short code. Maybe we can make it optional?

API changes:
- The type of `short_code` is `t -> string option` instead of `t -> string`

**Comment by mikeshulman** [comment]
Under what circumstances would one not want to have a short code?  I thought the whole point was that the user can always look up the short code in documentation; it seems to defeat the purpose if not all errors have a short code.

**Comment by favonia** [comment]
@mikeshulman Perhaps I was thinking too much about how to translate messages between different systems. When diving into the design documents of Rust, I found this comment: https://github.com/rust-lang/rustc-dev-guide/pull/967#issuecomment-733218283

They seem to avoid creating codes when the error contains everything and the code might not be useful for user. I was thinking about "how to translate those messages from Rust to asai" but of course there's no problem in translating messages from asai to Rust-style libraries.

**Comment by favonia** [comment]
Maybe a better idea is to make it optional only in our diagnostic type so that someone can write a translate if they want to, but keep the reporter API so that code is still mandatory. Otherwise, we should just abandon this idea (which is also fine).

**Comment by mikeshulman** [comment]
I think personally I would find it simpler to follow a general rule of "always have a short code", even if it sometimes doesn't add anything, than to have to make the extra decision of "do I make a short code for this?" every time I add a new error.  Even the author of that comment thinks it would be fine to have generic error codes for the cases that don't have specific details to add, which is precisely what I'm currently doing with parse errors.

**Comment by favonia** [comment]
Alright I will close this issue as "won't fix".
