### ISSUE TITLE
📄 Licensing of LSP server derived from Asai LSP

### ISSUE THREAD

**Issue by kentookura** [RedPRL/asai#163]
@favonia @jonsterling I used the Asai LSP as a basis for the forester LSP:

https://git.sr.ht/~jonsterling/ocaml-forester/log/lsp

I don't know too much about software licensing, what is the best course of action here?

**Comment by favonia** [comment]
@kentookura The current licensing of asai, Apache 2.0, is very compatible with GPL 3.0, in the sense that GPL 3.0 will satisfy the important requirements of Apache 2.0 (but not the other way around). None of these change who writes what, though. So "The RedPRL Development Team" still owns the copyright of the asai portion, and that portion is STILL licensed under Apache 2.0. It's just that if you make sure the required notice is there (detailed in the Apache 2.0 license text), and that you tell other people to follow the terms of GPL 3.0, then the other people will also fulfill the requirement of Apache 2.0, satisfying the conditions to use that portion of code.

In reality, though, these licenses only matter when the copyright owner is mad at you _and_ you fail to convince the court that your usage is fine. The social context of the open-source community made it relatively safe to use the source of free software project in another project _as long as you are not obviously ignoring the licensing._

PS: After https://github.com/RedPRL/asai/pull/156, even some of the Apache 2.0 requirements can be waved. For example, it waves some notice requirement when you ship the compiled executable.

**Comment by kentookura** [comment]
We have annotated the relevant files with the following SPDX header:

```ocaml
(*
 * SPDX-FileCopyrightText: 2024 The Forester Project Contributors AND The RedPRL Development Team
 *
 * SPDX-License-Identifier: GPL-3.0-or-later OR Apache-2.0
 *
 *)

```

**Comment by favonia** [comment]
@kentookura Thank you. The license identifier should be `GPL-3.0-or-later OR Apache-2.0 WITH LLVM-exception` or `GPL-3.0-or-later OR (Apache-2.0 WITH LLVM-exception)` (parentheses are optional in this case).
