### ISSUE TITLE
Replace `CamelCase` with `Camel_snake_case`

### ISSUE THREAD

**Issue by favonia** [RedPRL/asai#177]
@mikeshulman @kentookura The OCaml team has decided to go with `Camel_snake_case` for the standard library and I'd like to follow suit. Given that we will introduce so many breaking changes in version 0.4.0, I feel it's a reasonable time to make the change.

- https://github.com/ocaml/ocaml/issues/10778

**Comment by mikeshulman** [comment]
FWIW, the resolution of the linked issue (which was over 2 years ago) doesn't look to me like a decision to consistently use snake case for all module and constructor names in the standard library, only an observation that one camelcase module that was going to be added to the standard library had been renamed (for unspecified reasons).  Is there an explicit policy to use snake case everywhere in the standard library?  And not just for module names but also for constructor names?  As pointed out in that issue, there are still other camelcase modules in the standard library, such as `ListLabels` and friends.

**Comment by mikeshulman** [comment]
Not that I object to the change -- I prefer snake case myself, except sometimes for very short identifiers -- I'm just curious.

**Comment by favonia** [comment]
@mikeshulman That's correct, but I imagine that it's socially difficult to introduce even more inconsistencies from now on. Since the introduction of `In_channel` and `Out_channel`, their names have been discussed many times on the forum. I suppose more and more have become aware of the `Camel_snake` versus `CamelCase`.

[The official programming guidelines have a rule saying "Separate words by underscores",](https://ocaml.org/docs/guidelines#separate-words-by-underscores-int_of_string-not-intofstring) but it's not 100% clear whether that rule should apply to modules and constructors. However, it's certainly not wrong to use `Camel_snake` no matter how you interpret the guidelines.
