### ISSUE TITLE
Report multiple unrelated errors at once?

### ISSUE THREAD

**Issue by favonia** [RedPRL/asai#36]

**Comment by TOTBWF** [comment]
I see a couple of ways of doing this. The most naive is to use `try_with` in the driver to resume elaboration after a definition fails, but the UX seems like it could be suboptimal, as you could end up in a situation with a bunch of cascading errors.
Maybe there is some solution that uses a sort of error dependency graph, but I think it's a good idea to try and work out what behaviour we want here.

**Comment by favonia** [comment]
I'm closing this now because the use case seems to be collecting multiple unrelated errors from multiple threads (which we don't have right now), and it would complicate the current design a lot.
