### ISSUE TITLE
🔰 Is the quickstart tutorial good enough?

### ISSUE THREAD

**Issue by favonia** [RedPRL/asai#65]
Currently, there's a [quickstart tutorial.](https://redprl.org/asai/asai/quickstart.html) Is it good enough? Only a real experiment can tell. @jonsterling I think it's time to try out this library!

**Comment by jonsterling** [comment]
I'm excited that you have made a quickstart tutorial! I'll try this out as soon as I have time.

**Comment by favonia** [comment]
Writing the tutorial is helpful... now I realized the Span API is not good enough 😅

**Comment by favonia** [comment]
> I realized the Span API is not good enough 😅

Solved by #68 😎

**Comment by favonia** [comment]
Hi @solomon-b, if you feel adventurous, I think asai is ready for advanced beta users! I would like to extend my invitation to you as well (for polytt and maybe other things) 😎

**Comment by favonia** [comment]
@solomon-b A little bird told me it's already in use... but maybe you are still interested in reading the tutorial 😅

**Comment by solomon-b** [comment]
> @solomon-b A little bird told me it's already in use... but maybe you are still interested in reading the tutorial 😅

Haha, @TOTBWF is _heavily_ involved in PolyTT and we chose Ocaml specifically for the RedPRL library ecosystem. I'll take a look at this tutorial when I have some free time.

**Comment by favonia** [comment]
Thinking about it, I will probably release version 0.1.0 this weekend for my upcoming talk about these libraries. We can always update things later and things don't have to be perfect.

**Comment by favonia** [comment]
Updates: the tutorial just got two new sections, and 0.1.0 is now released! 😎

**Comment by favonia** [comment]
@solomon-b @jonsterling FYI: there's an on-going discussion about changing the name of `Logger`: #80.

**Comment by mikeshulman** [comment]
FWIW, I found the quickstart tutorial to be helpful in getting started.

**Comment by favonia** [comment]
I'm closing this given @mikeshulman's approval. Thanks! (We can still continue improving the tutorial.)
