### ISSUE TITLE
🖥️ Explicitly display the severity instead of using only colors

### ISSUE THREAD

**Issue by favonia** [RedPRL/asai#85]
The Tty backend should have explicitly printed out the severity (e.g., "ERROR") instead of _only_ relying on highlighting colors. This was suggested by @mikeshulman and I strongly agreed! I guess the remaining question is to find a good place in the Unicode art to add it:

Current output with location information:
```
    ╒══ examples/stlc/example.lambda
    │
  1 │ line1
  2 │ line2
    ┊
 20 │ line20
 21 │ line21
    ┷
 [E002] Message line 1
        Message line 2
```

Current output without location information:
```
 [E002] Message line 1
        Message line 2
```

**Comment by favonia** [comment]
Actually, this is worse than I thought, because severity was not printed when there's no location information.

**Comment by mikeshulman** [comment]
Maybe that explains why I wasn't seeing the colors either, because I don't have any location info yet.
