### ISSUE TITLE
📚 Document "Info" and "Hint" and maybe other severity levels

### ISSUE THREAD

**Issue by favonia** [RedPRL/asai#86]
This is another good question/suggestion by @mikeshulman. These two I believe were copied from the language server protocol (LSP) @TOTBWF. Is there a source of these terms? The official LSP specification does not seem to explain them?!

---

Let me just write down what I _thought_ they are:
- Bug: something went terribly wrong, and it's a bug; a kind end user may consider notifying the implementer
- Error: something went terribly wrong, but it's not a bug. The error was caused by external factors (e.g., no internet access) or users (e.g., syntax errors).
- Warning: something might have gone wrong, but it's okay
- Hint: some extra information directly related to the code, such as type information and refactor suggestion.
- Info: other extra information (e.g., the type checking was done!)

**Comment by TOTBWF** [comment]
This is definitely confusing, and I wish the spec provided more guidance on this... Here's my interpretation.
Diagnostics play a dual role: they are there to inform users of (possible) errors, but they are also one of the only ways to surface information to the user.

I interpret "Hint" as playing the former role: it is something that _could_ be an error, or at the very least a code smell. As an example, a good hint would be:

```
foo x = f x
^^^^^^^^^^^
Hint: You could eta-contract this.
```

As for "Info", this should mostly be used when you are doing notebook-style development: for instances, Coq's `Check` or `Print` commands. There's nothing potentially wrong with the code, and no changes should be made: it's just information that is attached to  a specific span.

**Comment by favonia** [comment]
@TOTBWF Thank you. Is there any "official" documentation we can cite? I prefer not to create new conventions here.

**Comment by mikeshulman** [comment]
How do LSP client editors actually treat Hint and Info in practice?

**Comment by favonia** [comment]
Reopen this to continue the conversation.

**Comment by favonia** [comment]
@mikeshulman Close this in favor of clearer #146.
