### ISSUE TITLE
🧮 Helper functions to recover byte offsets?

### ISSUE THREAD

**Issue by favonia** [RedPRL/asai#88]
I recently learned that the position type from [Fmlib_parse](https://github.com/hbr/fmlib) does not contain byte offsets. While I think it is more efficient if the parser library can provide byte offsets directly, we can also provide some (inefficient) helper function recovering the information by scanning the content from the start, counting the newline sequences.

This function should be added along with, or after the resolution of issue #87.

Yet² another good suggestion/question from @mikeshulman.

**Comment by TOTBWF** [comment]
We could also provide a batched interface: this should at least limit the inefficiency to a single pass through the file.
I'll also note that the normal caveats about column numbers apply here, and should come with a ⚠️ Disclaimer ⚠️.

**Comment by favonia** [comment]
> We could also provide a batched interface: this should at least limit the inefficiency to a single pass through the file.

It seems to me [fmlib](https://github.com/hbr/fmlib) is using bytes (`char`), so the "column number" in their position type seems to be byte offsets from the beginning of the line.

@mikeshulman I think you make a strong case to convince the authors of fmlib to include offsets from the beginning of the line. Their error reporter (arguably much less sophisticated than ours 😝) has [these two lines of code:](https://github.com/hbr/fmlib/blob/d1546212aefdecd7071af82903467f4bd0a0ee44/src/parse/source_extractor.ml#L336-L338)
```ocaml
let run_on_string  = Run_on.string  needs_more put put_end
let run_on_channel = Run_on.channel needs_more put put_end
```
which means they are reading the entire string or file from the _start_ to print out an error. It can be avoided, at least in the case of strings and files, if we also keep track of the byte offset.

---

PS: The parser I wrote earlier will recognize `\n`, `\r`, and `\r\n` as newlines, but it seems fmlib is recognizing only `\n` as newlines. I suppose things will be fine as long as we are only using Linux and macOS.

**Comment by mikeshulman** [comment]
> I think you make a strong case to convince the authors of fmlib to include offsets from the beginning of the line. 

Do you mean "from the beginning of the file"?

**Comment by favonia** [comment]
> > I think you make a strong case to convince the authors of fmlib to include offsets from the beginning of the line.
> 
> Do you mean "from the beginning of the file"?

Yes, sorry for the typo.

**Comment by mikeshulman** [comment]
The fmlib author says he can plan to include absolute byte positions in the next update.

**Comment by favonia** [comment]
_(Removing this issue from the 0.2.0 milestone because it would not be needed after the other library is updated.)_

**Comment by favonia** [comment]
We can re-open this when there's a need.
