### ISSUE TITLE
💬 Alternative API for (fully) structured messages?

### ISSUE THREAD

**Issue by favonia** [RedPRL/asai#89]
Yet³ another question/suggestion from @mikeshulman. The current asai library wants the implementer to directly write out the message when sending it. The other design is usid in cooltt, whene we send "structured" errors of this type:

```ocaml
type t =
  | MalformedCase
  | InvalidTypeExpression of CS.con
  | ExpectedSynthesizableTerm of CS.con_
  | CannotEliminate of Pp.env * S.tp
  | ExpectedSimpleInductive of Pp.env * S.tp
  | InvalidModifier of CS.con
  | ExpectedFailure of CS.decl
```

And then there's a pretty printer to turn these structured errors into elaborated messages. I am not sure how to have an API that works (nicely) for both, but at very least the design decision to "write the (unstructured) message when sending it" should be documented. This reminded me of the old debate between `catgets` and `gettext`, except that we are using high-level, rich constructors from OCaml types instead of integers in the case of `catgets`.

Any suggestions for redesigning the API?

**Comment by TOTBWF** [comment]
When I was first laying out `asai`, unstructured messages was explicit design choice that I made. The reasons for this were twofold. First, structured errors introduce a lot of programming overhead: instead of printing out a message, you have to add a case to a datatype, extend a pretty printing function, and potentially touch a bunch of module files. Second, it is inherently less flexible: if you want to use slightly different wording for the same class of errors, you need to introduce more cases in your datatype, which makes the overhead even worse. Finally, the extra structure you get doesn't ever get used in practice. If you look through the source code of other proof assistants, you will see that you never case on the errors outside of printing functions! 

I understand the appeal of using structured data for internationalization concerns, but a truly multi-lingual proof assistant is its own large research project, and one that I think is out-of-scope for `asai`. If there are any other arguments for structured errors I am more than happy to hear them, but I do not find this particular case that compelling.

**Comment by TOTBWF** [comment]
For programmer ergonomics, you can still expose an API that looks like structured errors: for instance, in [polytt](https://github.com/ToposInstitute/polytt/blob/main/lib/refiner/Eff.ml#L394C1-L401C11) we have functions that look like this:
```ocaml
  let type_error tp conn =
    let loc = Eff.read () in
    let env = Locals.qenv () in
    let ppenv = Locals.ppenv () in
    let qtp = Quote.quote ~env ~tp:D.Univ tp in
    Logger.fatalf ~loc:loc `TypeError "Expected %a, but got %s@."
      (S.pp ppenv Precedence.isolated) qtp
      conn
```

**Comment by favonia** [comment]
> Note that this is old code and does not represent asai best practices ATM

So the change (implemented in 0.1.0 already) is that asai will remember locations. @TOTBWF's code is still correct but might be redundant. We made the change after discovering that everyone implements their own way to remember locations.

**Comment by favonia** [comment]
@mikeshulman @jonsterling So we had some further internal discussions on this, and our current conclusion is that structured error messages might not be very useful. There have several potential uses of structured errors, but it seems each of them can be done with the current design (which is mostly unstructured except the message code):

1. **Localization:** a proper localization probably require fancier design, and the most common hack (`gettext`) is using the unstructured (format) strings as the key anyway. (It occasionally including extra parameters to distinguish contexts or grammatical subtleties).
2. **Separation of concerns** or **avoidance of duplicate code:** the counterpoint is that in practice the structured errors are not used beyond printing, and code duplication can be avoided by defining small helper functions whose only jobs are to omit those messages. It might also be easier to imagine good and relevant messages at the spot where the issue is detected.
3. **Something for end users to look up:** this is why the current design requires the implementer to assign concise message codes (as the minimum structuredness) to all messages.

Given this conclusion, I will turn this into an issue about documentation. We can revisit this if new arguments show up.

**Comment by mikeshulman** [comment]
Hmm, well, I'm not convinced.  Let me make one more try at explaining my view.

I don't know what a "proper localization" means, but it seems to me that some localization would always be better than none, and that it would be better to use a design that would make that easy.

If I understand correctly, `gettext` will not work with customized error strings that e.g. include a pretty-printing of the term that failed to typecheck, which was one of the use cases that you originally presented as a reason for *unstructured* messages.  Whereas looking up a structured error would always work even if the error is parametrized, and the pretty-printed terms could be dropped into the localized text as appropriate.

Along with localization (which I have no plans to implement myself anyway), a similar concern I mentioned is allowing the user to customize verbosity.

Personally, I want as little space as possible in my typechecking code to be taken up by generating error messages.  When I first wrote it without any error messages, it was in the `option` monad, which was nice and concise and I could concentrate on getting the algorithm correct.  I'd like to keep it as concise as possible and focused on the algorithm.  Emitting a structured error can be seen as part of the algorithm: this is the thing that went wrong in the algorithm.  *Describing* the thing that went wrong in English is not part of the algorithm, that's part of user interaction.

I don't see how structured errors introduce meaningfully more overhead.  In Asai's current design, when I add an error I already have to add a case to a datatype in the `Reporter` module and add match clauses to two functions in that module.  The only change I'm proposing would be that there's a third match clause in a pretty-printing function in that same module.  The programmer would be doing this at the same time as before, so the process of imagining a good and relevant message is still happening at the same time, i.e. when they're writing the code that generates the message.

I would argue that if you want to use "slightly different wording for the same class of errors" then you're making a mistake and that's actually a different class of errors.  (-:O

Finally, I see that much of what I want can be achieved by writing individual messaging functions, but that seems like *more* overhead.  If structure isn't required by the design, then it would be easy to get into a situation where some messages are done structured and others are more unstructured, which would be confusing and harder to maintain.

All that said, of course you're the authors of the library, and if that's what you want then I can work around it.  In fact I can make the errors in my `Logger.t` structured and write my own pretty-printing function for them in my own Reporter module as a wrapper around `emit`/`fatal`.  (-:

**Comment by favonia** [comment]
@mikeshulman Thank you. I think what I can try is to put together a structured version. I actually remain relatively undecided, and after pondering on it more, I feel there might be a way to provide both structured and unstructured interfaces. Following the "who contributes most decides" meta-principle, I think I have the authority to override the opinions of @jonsterling and @TOTBWF. 😂

I do have questions about the diagnostics generated by the structured versions:
1. Currently, unstructured messages are used for backtraces, main messages, and additional messages. Should all of them become structured, or just the main messages? Currently I assume it's just the main message.
2. If we decide to format a structured message into an unstructured one to recycle existing code, is it okay/expected to reuse the structured message as the message code?
3. Should we format structured error messages into an unstructured one the moment the message is sent? The impact is that `try_with`, `map_text`, etc will work with _unstructured_ ones instead of structured ones. Though, if we reuse structured messages as message codes, then the original structured messages are still available.

Another path forward might be experimenting with the wrapping you have in your mind, and then we can generalize it and put it into the generic library. The mechanism to remember locations was added for the same reason.

**Comment by TOTBWF** [comment]
As another example of where structured errors go wrong: if you are using a nameless representation of variables, you will need to capture the pretty printing environment inside of the error, instead of directly using the pretty-printing environment you have at hand. This is a potential source of inefficiency: using a mutable pretty-printing environment is no longer a possibility.

I suppose the question at hand for me is this: if we do support a structured interface, does this only apply when constructing the messages, or in the effect handlers. The latter seems like a much more reasonable approach to me.

**Comment by mikeshulman** [comment]
I'm happy to experiment with my wrapper.  I don't think I know enough about the internals of asai to understand what you mean by your three questions.

The point about mutable data is an interesting one.  I think I was envisioning turning the structured errors into strings immediately when `emit` is called, so that any mutable data would refer correctly to its state at that point in time, rather than saving the structured errors and doing something with them later.  But then, I was also envisioning the message even being printed immediately when `emit` is called, so that there wouldn't be any other option than turning it into a string immediately.  Are you "saving" the error codes somehow and doing something different with them later?

**Comment by mikeshulman** [comment]
I do see that the error codes are being stored in a `diagnostic`, which can be inspected elsewhere and so on.  But are they saved somewhere that persists *after* `emit` returns to the caller?

**Comment by favonia** [comment]
> I'm happy to experiment with my wrapper. I don't think I know enough about the internals of asai to understand what you mean by your three questions.

Thanks. I suggest the second path then---please wrap the current library to implement whatever you want, and we will take a look and see what the alternative API should be. I think as long as I still keep the current API for unstructured messages, no one will (really) complain. 😀

> I do see that the error codes are being stored in a `diagnostic`, which can be inspected elsewhere and so on. But are they saved somewhere that persists _after_ `emit` returns to the caller?

No. Once a diagnostic is rendered by the backend, it is gone. Of course, one can implement a backend which keeps all the diagnostics. The backend is a function of type `Code.t Diagnostic.t -> unit` and it can do anything (including keeping diagnostics) there.

**Comment by mikeshulman** [comment]
Here's a way to implement a wrapper that keeps the structured data out of the type `Code.t`.  The idea is to bundle the individual messaging functions up into one, using a type parameter to make sure they get the right arguments for the error code.  It's easy to include an unstructured error as a special case of a structured one by having it take just one string argument and passing it through.

```ocaml
module Code = struct
  type _ code =
    Type_error : (Term.t * Value.t) code
    Unbound_variable : string code
    Unstructured : string code

  type t = Code : 'a code -> t

  let die : type a b. a code -> a -> b =
    fun err arg ->
    match (err, arg) with
    | Type_error, (tm, ty) -> 
      fatalf (Code err) "Type error: %s doesn't have type %s" (Term.to_string tm) (Value.to_string ty)
    | Unbound_variable, name ->
      fatalf (Code err) "Unbound variable: %s" name
    | Unstructured, msg ->
      fatal (Code err) msg
end

```

**Comment by favonia** [comment]
@mikeshulman The use of GADT is very interesting! Yes, that's a clean way to separate things out. On the other hand, I don't feel there's a significant downside of keeping structured data in `Code.t`. Therefore, maybe it is okay to keep the data there.

---

In any case, the wrapper means that a structured message will be (morally) converted into an unstructured one the moment it is sent. @TOTBWF and I were wondering whether it should remain "structured" longer in the system, and I feel everyone agrees that there's no need to come up with a different diagnostic type or a different handler to keep messages structured.

I feel an easy way to satisfy everyone is to change the meaning of the `code` field in the type `Diagnostic.t` so that it means _"structured bits of the main message"_ not just _"message code"._ When used in the "unstructured" way, the `code` is a coarse classification of messages. When used in the "structured" way, the `code` carries the complete information. I wonder if anyone has a suggestion for a new name for the `code` field (or maybe "`code`" is fine?). I'm pretty bad at coming up with good names. @TOTBWF @mmcqd

Suppose there's a good name for the new `code` field. Then, here is my plan to close this issue:

1. Keep the current `Reporter` as it is.
2. Introduce `StructuredReporter` where the API is expecting structured messages. In comparison with the unstructured usage, the implementer will have to implement a function of type `t -> Diagnostic.text`.
3. Write a _separate_ tutorial showing the alternative setup with `StructuredReporter`.

**Comment by mikeshulman** [comment]
That sounds fine to me!

**Comment by favonia** [comment]
@mikeshulman Do you have a suggestion for the new field that means "structured bits of the (main) message"?
